services:
  postgres:
    image: ankane/pgvector
    container_name: caballo-money-web-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data_caballo-money:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=caballo-money

volumes:
  postgres_data_caballo-money:
